[package]
name = "read_it_to_me"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.0.1"
aws-sdk-polly = "1.3.0"
tokio = { version = "1.0", features = ["full"] }
rodio = "0.17.1"
chrono = "0.4.40"
